source 'https://rubygems.org'
ruby '2.5.3'

gem 'activerecord'
gem 'aws-sdk-s3', '~> 1'
gem 'dotenv'
gem 'pg'
gem 'rake'
gem 'standalone_migrations'

group :development, :test do
  gem 'rspec'
  gem 'byebug'
  gem 'simplecov'
end
